name: Release
on:
  push:
    branches:
      - master
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run browserify
      - name: Semantic Release
        id: semantic-release
        uses: BrightspaceUI/actions/semantic-release@master
        with:
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
          NPM: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Assume role
        if: steps.semantic-release.outputs.VERSION != ''
        uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: "arn:aws:iam::771734770799:role/cdn-infrastructure-ifrau"
          role-duration-seconds: 3600
          aws-region: us-east-1
      - name: Publish to CDN
        if: steps.semantic-release.outputs.VERSION != ''
        run: |
            echo "Publishing to the CDN as version: ${{ steps.semantic-release.outputs.VERSION }}"
            npx frau-publisher --v="${{ steps.semantic-release.outputs.VERSION }}" --f="./dist/**/*.js" --m="lib" --t="ifrau"
        env:
          # cred variables set in the "Assume role" step
          AWS_DEFAULT_REGION: us-east-1
